%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\apoorvgarg\Dropbox\FHWA_Matlab\Apoorv\Steel Project Functions\Steel Project Files\Project#27-Steel_Exploration Data.xlsx
%    Worksheet: CPT CPT-08-151
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/08/23 19:13:35

%% for all CPT sheets
function [fileName, CPTSheetNames, Project_CPT ] = getCPTSheetData_GUI_mod( p1,f1 )
fileName = strcat(p1,f1);
[~,sheetName,~] = xlsfinfo(fileName);
 sheetName = sheetName';

charSheetName = char(sheetName);

for i = 1:1:length(sheetName)
 if strcmp(charSheetName(i,1),'C') && strcmp(charSheetName(i,2),'P')&& strcmp(charSheetName(i,3),'T') 
CPTSheetName(i) = sheetName(i);
 end
end
CPTSheetNames = CPTSheetName(~cellfun(@isempty,CPTSheetName));


clearvars x i CPTSheetName charSheetName;
for i = 1:1:length(CPTSheetNames)

%% Import the data
[~, ~, raw0_0] = xlsread(fileName,CPTSheetNames{i},'C20:D3016');
[~, ~, raw0_1] = xlsread(fileName,CPTSheetNames{i},'G20:L3016');
[~, ~, raw0_2] = xlsread(fileName,CPTSheetNames{i},'O20:O3016');
[~, ~, raw0_3] = xlsread(fileName,CPTSheetNames{i},'R20:W3016');
[~, ~, raw0_4] = xlsread(fileName,CPTSheetNames{i},'Z20:AC3016');
[~, ~, raw0_5] = xlsread(fileName,CPTSheetNames{i},'AE20:AF3016');
[~, ~, raw0_6] = xlsread(fileName,CPTSheetNames{i},'AH20:AH3016');
[~, ~, raw0_7] = xlsread(fileName,CPTSheetNames{i},'AJ20:AL3016');
[~, ~, raw0_8] = xlsread(fileName,CPTSheetNames{i},'AP20:AP3016');
raw = [raw0_0,raw0_1,raw0_2,raw0_3,raw0_4,raw0_5,raw0_6,raw0_7,raw0_8];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]);

%% Allocate imported array to column variable names
GSW_ExtraData = cellVectors(:,1);
GSW_Unit = cellVectors(:,2);
Elevation = cellVectors(:,3);
Depth = cellVectors(:,4);
Qc = cellVectors(:,5);
Fs = cellVectors(:,6);
MeasuredPoreWaterPress = cellVectors(:,7);
qt = cellVectors(:,8);
FrictionRatio = cellVectors(:,9);
SoiBehaviorIndex = cellVectors(:,10);
SoilBehaviorType = cellVectors(:,11);
OCR = cellVectors(:,12);
FrictionAngle = cellVectors(:,13);
Cohesion = cellVectors(:,14);
SPTBlowCount = cellVectors(:,15);
DepthToBottomLayer = cellVectors(:,16);
LayerThickness = cellVectors(:,17);
DepthToWater = cellVectors(:,18);
USCScode = cellVectors(:,19);
PrimarySoilDesc = cellVectors(:,20);
SecondarySoilDesc = cellVectors(:,21);
LayerDesc = cellVectors(:,22);
GenSPT_BlowCount = cellVectors(:,23);
GenSPT_BlowIncrement = cellVectors(:,24);
GenCohesion = cellVectors(:,25);
GenUnitWeight = cellVectors(:,26);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw0_2 raw0_3 raw0_4 raw0_5 raw0_6 raw0_7 raw0_8 cellVectors;

%% Create Script
structureSheetName = matlab.lang.makeValidName(CPTSheetNames{i});
Project_CPT.(structureSheetName) = struct('GSW_ExtraData',{GSW_ExtraData},'GSW_Unit',{GSW_Unit}...
,'Elevation',{Elevation} ,'Depth',{Depth} ,'Qc',{Qc} ,'Fs',{Fs},'qt',{qt} ,'FrictionRatio',{FrictionRatio},...
'SoilBehaviorType',{SoilBehaviorType},'Cohesion',{Cohesion},'SPTBlowCount',{SPTBlowCount},'DepthToBottomLayer',{DepthToBottomLayer},...
'LayerThickness',{LayerThickness},'USCScode',{USCScode},'GenSPT_BlowCount',{GenSPT_BlowCount}, 'GenSPT_BlowIncrement',...
{GenSPT_BlowIncrement},'GenCohesion',{GenCohesion},'PrimarySoilDesc',{PrimarySoilDesc},...
'SecondarySoilDesc',{SecondarySoilDesc});
end
end