
function [GeneralizedPileSheetNames, Project_GeneralizedPile ] = getGeneralizedPileSheetData_GUI(p1,f1)
fileName = strcat(p1,f1);
[~,sheetName,~] = xlsfinfo(fileName);
 sheetName = sheetName';

charSheetName = char(sheetName);

for i = 1:1:length(sheetName)
 if strcmp(charSheetName(i,1),'G') && strcmp(charSheetName(i,2),'e')&& strcmp(charSheetName(i,3),'n')&& strcmp(charSheetName(i,4),'e')&& strcmp(charSheetName(i,5),'r')&& strcmp(charSheetName(i,6),'a')&& strcmp(charSheetName(i,7),'l')...
         && strcmp(charSheetName(i,8),'i')&& strcmp(charSheetName(i,9),'z')&& strcmp(charSheetName(i,10),'e')&& strcmp(charSheetName(i,11),'d')
GeneralizedPileSheetName(i) = sheetName(i);
 end
end
GeneralizedPileSheetNames = GeneralizedPileSheetName(~cellfun(@isempty, GeneralizedPileSheetName));

clearvars x i GeneralizedPileSheetName charSheetName;

for i = 1:1:length(GeneralizedPileSheetNames)



%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\apoorvgarg\Dropbox\FHWA_Matlab\Apoorv\Steel Project Functions\Steel Project Files\Project#46-Steel_Test Pile Section and Installation Data.xlsx
%    Worksheet: Generalized Soil Layer TP-6
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/08/11 12:18:40

%% Import the data
[~, ~, raw0_0] = xlsread(fileName,GeneralizedPileSheetNames{i},'C19:D50');
[~, ~, raw0_1] = xlsread(fileName,GeneralizedPileSheetNames{i},'F19:G50');
[~, ~, raw0_2] = xlsread(fileName,GeneralizedPileSheetNames{i},'I19:J50');
[~, ~, raw0_3] = xlsread(fileName,GeneralizedPileSheetNames{i},'L19:L50');
[~, ~, raw0_4] = xlsread(fileName,GeneralizedPileSheetNames{i},'N19:Q50');
[~, ~, raw0_5] = xlsread(fileName,GeneralizedPileSheetNames{i},'T19:T50');
[~, ~, raw0_6] = xlsread(fileName,GeneralizedPileSheetNames{i},'Y19:Y50');
[~, ~, raw0_7] = xlsread(fileName,GeneralizedPileSheetNames{i},'AA19:AD50');
raw = [raw0_0,raw0_1,raw0_2,raw0_3,raw0_4,raw0_5,raw0_6,raw0_7];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]);

%% Allocate imported array to column variable names
GSE_ExtraData = cellVectors(:,1);
GSE_Units = cellVectors(:,2);
Depth = cellVectors(:,3);
USCSCode = cellVectors(:,4);
PrimarySoilDesc = cellVectors(:,5);
SecondarySoilDesc = cellVectors(:,6);
LayerDesc = cellVectors(:,7);
SPTNumber = cellVectors(:,8);
SPTIncrement = cellVectors(:,9);
Cohesion = cellVectors(:,10);
FrictionAngle = cellVectors(:,11);
UnitWeight = cellVectors(:,12);
OCR = cellVectors(:,13);
LiquidLimit = cellVectors(:,14);
PlasticLimit = cellVectors(:,15);
PlasticityIndex = cellVectors(:,16);
RQD = cellVectors(:,17);

%% Create Structure for Generalized Pile data

structureSheetName = matlab.lang.makeValidName(GeneralizedPileSheetNames{i});
Project_GeneralizedPile.(structureSheetName) = struct('GSE_ExtraData',{GSE_ExtraData},'GSE_Units',{GSE_Units},'Depth',{Depth},'USCSCode',...
    {USCSCode},'PrimarySoilDesc',{PrimarySoilDesc},'SecondarySoilDesc',{SecondarySoilDesc},'LayerDesc',{LayerDesc},...
    'SPTNumber',{SPTNumber},'SPTIncrement',{SPTIncrement},'Cohesion',{Cohesion},'FrictionAngle',{FrictionAngle},...
    'UnitWeight',{UnitWeight},'OCR',{OCR},'LiquidLimit',{LiquidLimit},'PlasticLimit',{PlasticLimit},'PlasticityIndex',...
    {PlasticityIndex},'RQD',{RQD});


%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw0_2 raw0_3 raw0_4 raw0_5 raw0_6 raw0_7 cellVectors;

end
end