function [fileName, STEELSheetNames, Project_Steel ] = getSteelPiledata_GUI( p2,f2 )
fileName = strcat(p2,f2);
[~,sheetName,~] = xlsfinfo(fileName);
 sheetName = sheetName';

charSheetName = char(sheetName);

for i = 1:1:length(sheetName)
 if (strcmp(charSheetName(i,1),'S') && strcmp(charSheetName(i,2),'T')&& strcmp(charSheetName(i,3),'E')&& strcmp(charSheetName(i,4),'E')&& strcmp(charSheetName(i,5),'L'))|| (strcmp(charSheetName(i,1),'C') && strcmp(charSheetName(i,2),'O')&& strcmp(charSheetName(i,3),'N')&& strcmp(charSheetName(i,4),'C')&& strcmp(charSheetName(i,5),'R'))
STEELSheetName(i) = sheetName(i);
 end
end
STEELSheetNames = STEELSheetName(~cellfun(@isempty,STEELSheetName));


clearvars x i STEELSheetName charSheetName;
for i = 1:1:length(STEELSheetNames)

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\apoorvgarg\Dropbox\FHWA_Matlab\Apoorv\Steel Project Functions\Project#24-Steel_Test Pile Section and Installation Data.xlsx
%    Worksheet: STEEL Section TP-9
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/06/09 11:48:01

%% Import the data
[~, ~, raw] = xlsread(fileName,STEELSheetNames{i},'D18:N18');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SectionLength = data(:,1);
TopDepth = data(:,2);
BottomDepth = data(:,3);
TopElevation = data(:,4);
BottomElevation = data(:,5);
WallThickness = data(:,6);
OuterDiameter = data(:,7);
InnerDiameter = data(:,8);
WeightperUnit = data(:,9);
SteelYieldStrength = data(:,10);
SteelModulus = data(:,11);

%% Clear temporary variables
clearvars data raw R;

%% create structure
nestedStructure_Steel = matlab.lang.makeValidName(STEELSheetNames{i});

Project_Steel.(nestedStructure_Steel) = struct('SectionLength',SectionLength, 'TopDepth',TopDepth, 'BottomDepth',BottomDepth, 'TopElevation',TopElevation,'BottomElevation',BottomElevation, 'WallThickness',WallThickness,...
    'OuterDiameter',OuterDiameter, 'InnerDiameter',InnerDiameter, 'WeightperUnit',WeightperUnit, 'SteelYieldStrength',SteelYieldStrength, 'SteelModulus',SteelModulus); 

end
end