function OpenFile= openFileMethod_GUI()


%% Open the File Name
[filename] = uigetfile(...
 {'*.xls';'*.xlsx';'*.*'},...
 'Open');

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\apoorvgarg\Dropbox\FHWA_Matlab\Apoorv\Steel Project Functions\GUI\check.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/08/09 16:24:36

%% Import the data
[~, ~, raw] = xlsread(filename,'Sheet1','A2:F41');
[rows, columns] = size(raw);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[3,4]);
raw = raw(:,[1,2,5,6]);
 raw(~cellfun('isempty',raw))  ;
 cellVectors(~cellfun('isempty',cellVectors))  ;

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
StartElev = data(:,1);
EndElev = data(:,2);
SoilType = cellVectors(:,1);
RelativeDensity = cellVectors(:,2);
Cohesion = data(:,3);
UnitWeight = data(:,4);


%% Define Structure
OpenFile.StartElev = StartElev(~isnan(StartElev));
OpenFile.EndElev = EndElev(~isnan(EndElev));

OpenFile.SoilType = SoilType(~isnan(EndElev));
OpenFile.RelativeDensity = (RelativeDensity(~isnan(EndElev)));

OpenFile.Cohesion =(Cohesion(~isnan(Cohesion)));
OpenFile.UnitWeight = UnitWeight(~isnan(UnitWeight));
OpenFile.Layers = rows;


%% Clear temporary variables
clearvars data raw cellVectors R;