%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\apoorvgarg\Dropbox\FHWA_Matlab\Apoorv\Steel Project Functions\Project#24-Steel_Exploration Data.xlsx
%    Worksheet: Lab
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/06/08 13:55:02
function [tBlb,index] = sortLabdata_GUI(p1,f1 )
fileName = strcat(p1,f1);
[~,sheetName,~] = xlsfinfo(fileName);
 sheetName = sheetName';

charSheetName = char(sheetName);

for i = 1:1:length(sheetName)
 if strcmp(charSheetName(i,1),'L') && strcmp(charSheetName(i,2),'a')&& strcmp(charSheetName(i,3),'b')
LabSheetName(i) = sheetName(i);
 end
end
LabSheetNames = LabSheetName(~cellfun(@isempty, LabSheetName));


clearvars x i LabSheetName charSheetName;
for i = 1:1:length(LabSheetNames)
%% Import the data
[~, ~, raw] = xlsread(fileName,LabSheetNames{i},'A19:AN620');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,4,5,6,23,34,35,40]);
raw = raw(:,[1,3,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,36,37,38,39]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
VarName1{i} = data(:,1);
ExplorationDesignation{i} = cellVectors(:,1);
Depth{i} = data(:,2);
PDF{i} = cellVectors(:,2);
USCSCode{i} = cellVectors(:,3);
ASTMCode{i} = cellVectors(:,4);
MoistueContent{i} = data(:,3);
TotalUnit{i} = data(:,4);
DryDensity{i} = data(:,5);
RelativeDensity{i} = data(:,6);
UnitWeight_Max{i} = data(:,7);
UnitWeight_Min{i} = data(:,8);
LiquidLimit{i} = data(:,9);
PlasticLimit{i} = data(:,10);
PlasticityIndex{i} = data(:,11);
Gravel{i} = data(:,12);
Sand{i}= data(:,13);
Fines{i} = data(:,14);
ClayFraction{i} = data(:,15);
D10{i} = data(:,16);
D30{i} = data(:,17);
D60{i}= data(:,18);
GrainSizeLabData{i} = cellVectors(:,5);
PermK{i} = data(:,19);
saturation{i} = data(:,20);
CompIndex{i}= data(:,21);
ReCompIndex{i} = data(:,22);
VoidRatio{i} = data(:,23);
CoeffConsol{i} = data(:,24);
CoeffComp{i} = data(:,25);
T90{i} = data(:,26);
PreconsolPress{i} = data(:,27);
OCR{i} = data(:,28);
ConsolLabData{i} = cellVectors(:,6);
ShearTestCode{i} = cellVectors(:,7);
Cohesion{i} = data(:,29);
FrictionAngle{i} = data(:,30);
EffectiveCohesion{i} = data(:,31);
EffectiveFrictionAngle{i} = data(:,32);
ShearTestLabdata{i} = cellVectors(:,8);


for q = 1:length(ExplorationDesignation{i})
if isnumeric(ExplorationDesignation{1,i}{q})
    ExplorationDesignation{1,i}{q} = num2str(ExplorationDesignation{1,i}{q});
else continue

end
end

%% Clear temporary variables
clearvars data raw cellVectors R;
end
%% Concatenate Matrix

if length(LabSheetNames)== 2
VarName_Combined = vertcat(VarName1{1},VarName1{2});
Depth_Combined = vertcat(Depth{1},Depth{2});
ExplorationDesignation_Combined = vertcat(ExplorationDesignation{1},ExplorationDesignation{2});
PDF_Combined = vertcat(PDF{1},PDF{2});
USCSCode_Combined = vertcat(USCSCode{1},USCSCode{2});
ASTMCode_Combined = vertcat(ASTMCode{1},ASTMCode{2});
MoistueContent_Combined= vertcat(MoistueContent{1},MoistueContent{2});
TotalUnit_Combined = vertcat(TotalUnit{1},TotalUnit{2});
DryDensity_Combined = vertcat(DryDensity{1},DryDensity{2});
RelativeDensity_Combined = vertcat(RelativeDensity{1},RelativeDensity{2});
UnitWeight_Max_Combined = vertcat(UnitWeight_Max{1},UnitWeight_Max{2});
UnitWeight_Min_Combined = vertcat(UnitWeight_Min{1},UnitWeight_Min{2});
LiquidLimit_Combined = vertcat(LiquidLimit{1},LiquidLimit{2});
PlasticLimit_Combined = vertcat(PlasticLimit{1},PlasticLimit{2}) ;
PlasticityIndex_Combined = vertcat(PlasticityIndex{1},PlasticityIndex{2});
Gravel_Combined = vertcat(Gravel{1},Gravel{2});
Sand_Combined= vertcat(Sand{1},Sand{2});
Fines_Combined = vertcat(Fines{1},Fines{2});
ClayFraction_Combined = vertcat(ClayFraction{1},ClayFraction{2});
D10_Combined = vertcat(D10{1},D10{2});
D30_Combined = vertcat(D30{1},D30{2});
D60_Combined= vertcat(D60{2},D60{2});
GrainSizeLabData_Combined = vertcat(GrainSizeLabData{1},GrainSizeLabData{2});
PermK_Combined = vertcat(PermK{1},PermK{2});
saturation_Combined = vertcat(saturation{1},saturation{2});
CompIndex_Combined= vertcat(CompIndex{1},CompIndex{2});
ReCompIndex_Combined = vertcat(ReCompIndex{1},ReCompIndex{2});
VoidRatio_Combined = vertcat(VoidRatio{1},VoidRatio{2});
CoeffConsol_Combined = vertcat(CoeffConsol{1},CoeffConsol{2});
CoeffComp_Combined = vertcat(CoeffComp{1},CoeffComp{2});
T90_Combined = vertcat(T90{1},T90{2});
PreconsolPress_Combined = vertcat(PreconsolPress{1},PreconsolPress{2});
OCR_Combined = vertcat(OCR{1},OCR{2});
ConsolLabData_Combined = vertcat(ConsolLabData{1},ConsolLabData{2});
ShearTestCode_Combined = vertcat(ShearTestCode{1},ShearTestCode{2});
Cohesion_Combined = vertcat(Cohesion{1},Cohesion{2});
FrictionAngle_Combined = vertcat(FrictionAngle{1},FrictionAngle{2});
EffectiveCohesion_Combined = vertcat(EffectiveCohesion{1},EffectiveCohesion{2});
EffectiveFrictionAngle_Combined = vertcat(EffectiveFrictionAngle{1},EffectiveFrictionAngle{2});
ShearTestLabdata_Combined = vertcat(ShearTestLabdata{1},ShearTestLabdata{2});

elseif length(LabSheetNames)==1
    
VarName_Combined = vertcat(VarName1{1});
Depth_Combined = vertcat(Depth{1});
ExplorationDesignation_Combined = vertcat(ExplorationDesignation{1});
PDF_Combined = vertcat(PDF{1});
USCSCode_Combined = vertcat(USCSCode{1});
ASTMCode_Combined = vertcat(ASTMCode{1});
MoistueContent_Combined= vertcat(MoistueContent{1});
TotalUnit_Combined = vertcat(TotalUnit{1});
DryDensity_Combined = vertcat(DryDensity{1});
RelativeDensity_Combined = vertcat(RelativeDensity{1});
UnitWeight_Max_Combined = vertcat(UnitWeight_Max{1});
UnitWeight_Min_Combined = vertcat(UnitWeight_Min{1});
LiquidLimit_Combined = vertcat(LiquidLimit{1});
PlasticLimit_Combined = vertcat(PlasticLimit{1}) ;
PlasticityIndex_Combined = vertcat(PlasticityIndex{1});
Gravel_Combined = vertcat(Gravel{1});
Sand_Combined= vertcat(Sand{1});
Fines_Combined = vertcat(Fines{1});
ClayFraction_Combined = vertcat(ClayFraction{1});
D10_Combined = vertcat(D10{1});
D30_Combined = vertcat(D30{1});
D60_Combined= vertcat(D60{1});
GrainSizeLabData_Combined = vertcat(GrainSizeLabData{1});
PermK_Combined = vertcat(PermK{1});
saturation_Combined = vertcat(saturation{1});
CompIndex_Combined= vertcat(CompIndex{1});
ReCompIndex_Combined = vertcat(ReCompIndex{1});
VoidRatio_Combined = vertcat(VoidRatio{1});
CoeffConsol_Combined = vertcat(CoeffConsol{1});
CoeffComp_Combined = vertcat(CoeffComp{1});
T90_Combined = vertcat(T90{1});
PreconsolPress_Combined = vertcat(PreconsolPress{1});
OCR_Combined = vertcat(OCR{1});
ConsolLabData_Combined = vertcat(ConsolLabData{1});
ShearTestCode_Combined = vertcat(ShearTestCode{1});
Cohesion_Combined = vertcat(Cohesion{1});
FrictionAngle_Combined = vertcat(FrictionAngle{1});
EffectiveCohesion_Combined = vertcat(EffectiveCohesion{1});
EffectiveFrictionAngle_Combined = vertcat(EffectiveFrictionAngle{1});
ShearTestLabdata_Combined = vertcat(ShearTestLabdata{1});
end

%% sort the variables
tBla = table(VarName_Combined, Depth_Combined, ExplorationDesignation_Combined, PDF_Combined, USCSCode_Combined,ASTMCode_Combined,MoistueContent_Combined,TotalUnit_Combined,DryDensity_Combined,RelativeDensity_Combined,UnitWeight_Max_Combined,...
    UnitWeight_Min_Combined,LiquidLimit_Combined,PlasticLimit_Combined,PlasticityIndex_Combined,Gravel_Combined,Sand_Combined,Fines_Combined,ClayFraction_Combined,D10_Combined,D30_Combined,D60_Combined,GrainSizeLabData_Combined,...
    PermK_Combined,saturation_Combined,CompIndex_Combined,ReCompIndex_Combined,VoidRatio_Combined,CoeffConsol_Combined,CoeffComp_Combined,T90_Combined,PreconsolPress_Combined,OCR_Combined,ConsolLabData_Combined,ShearTestCode_Combined,...
    Cohesion_Combined,FrictionAngle_Combined,EffectiveCohesion_Combined,EffectiveFrictionAngle_Combined,ShearTestLabdata_Combined) ;

[tBlb,index] = sortrows(tBla,[3 2]);

ind = find(isnan(tBlb.Depth_Combined));
tBlb(ind,:)=[];
% writetable(tBlb,strcat('sortedLabData_Project',sprintf('#%i.xlsx',ProjectNumber)));



end